# =====================================================================
# reset-dependencies.ps1
#
# Resets the template back to the pristine post-clone state - the exact
# inverse of scripts\setup-dependencies.ps1, in the reverse order:
#
#   [1/3] HeliosView's own dependencies - delegated to
#         HeliosView/scripts/reset-dependencies.ps1, which deinitializes and
#         removes stdexec, the Boost superproject + its libraries, blend2d,
#         asmjit, and deletes the downloaded OpenSSL / WebView2 SDK /
#         cacert.pem / *.nupkg under HeliosView/third_party/.
#   [2/3] The HeliosView submodule itself (deinit + worktree removal).
#   [3/3] frontend/node_modules (regenerated by `npm install`).
#
# Order matters: HeliosView's own reset runs first, while its worktree still
# exists, so it can clean up after itself.
#
# SAFETY: this only removes git submodule working trees, gitignored build
# inputs (third_party downloads, node_modules) and their git metadata. It
# never touches tracked files, your working branch or uncommitted code.
#
# Usage:
#   .\scripts\reset-dependencies.ps1
#   .\scripts\reset-dependencies.ps1 -KeepGitCache    # keep git object cache
#   .\scripts\reset-dependencies.ps1 -OnlyDownloads   # only the downloaded packages
#   .\scripts\reset-dependencies.ps1 -OnlySubmodules  # only the git submodules
#   .\scripts\reset-dependencies.ps1 -KeepFrontend    # leave node_modules alone
# =====================================================================

param(
    [switch]$KeepGitCache,
    [switch]$OnlyDownloads,
    [switch]$OnlySubmodules,
    [switch]$KeepFrontend,
    [switch]$Force,

    # Deprecated: the old template wrapper forwarded this to HeliosView's
    # script, which never accepted it (it takes -KeepGitCache /
    # -OnlyDownloads / -OnlySubmodules). Kept as an alias for "reset only the
    # submodules, keep the downloaded packages".
    [switch]$KeepDownloads
)

$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $RepoRoot

# ---------------------------------------------------------------------
# Native-command helpers.
#
# Windows PowerShell turns a native command's stderr into a terminating error
# when $ErrorActionPreference is 'Stop' - and git prints deinit notices and
# failures on stderr, so a single `git ... 2>$null` would abort this script
# half-way through a reset. These wrappers relax the preference for the
# duration of the call (the preference variable is scoped, so the caller is
# unaffected) and surface the exit code / output instead.
# ---------------------------------------------------------------------
function Invoke-Native {
    param([string]$FilePath, [string[]]$Arguments, [string]$WorkingDirectory)
    $prevEap = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        if ($WorkingDirectory) { Push-Location $WorkingDirectory }
        & $FilePath @Arguments
        $code = $LASTEXITCODE
    } finally {
        if ($WorkingDirectory) { Pop-Location }
        $ErrorActionPreference = $prevEap
    }
    return $code
}

function Get-NativeOutput {
    param([string]$FilePath, [string[]]$Arguments)
    $prevEap = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        return @(& $FilePath @Arguments 2>$null)
    } finally {
        $ErrorActionPreference = $prevEap
    }
}

Write-Host "==========================================================" -ForegroundColor Yellow
Write-Host " HeliosView-Template Reset Dependencies" -ForegroundColor Yellow
Write-Host " Working directory: $RepoRoot" -ForegroundColor Yellow
Write-Host "==========================================================" -ForegroundColor Yellow

if ($KeepDownloads -and (-not $OnlySubmodules)) {
    Write-Warning "-KeepDownloads is deprecated; it maps to -OnlySubmodules (keep the downloaded packages, reset the submodules)."
    $OnlySubmodules = $true
}

$cleanSubmodules = -not $OnlyDownloads

# ---------------------------------------------------------------------
# 1. HeliosView's own dependencies
# ---------------------------------------------------------------------
Write-Host "`n[1/3] Resetting HeliosView's own dependencies..." -ForegroundColor Cyan

$heliosResetPs1 = Join-Path $RepoRoot 'HeliosView/scripts/reset-dependencies.ps1'
if (Test-Path $heliosResetPs1) {
    $resetArgs = @{}
    if ($KeepGitCache)   { $resetArgs['KeepGitCache'] = $true }
    if ($OnlyDownloads)  { $resetArgs['OnlyDownloads'] = $true }
    if ($OnlySubmodules) { $resetArgs['OnlySubmodules'] = $true }
    if ($Force)          { $resetArgs['Force'] = $true }

    try {
        & $heliosResetPs1 @resetArgs
    } catch {
        Write-Error "HeliosView reset script failed: $($_.Exception.Message)"
        exit 1
    }
    Set-Location $RepoRoot   # the delegated script moves the session's cwd
} else {
    Write-Warning "HeliosView reset script not found: $heliosResetPs1 (already reset?)"
}

# ---------------------------------------------------------------------
# 2. The HeliosView submodule itself
# ---------------------------------------------------------------------
if ($cleanSubmodules) {
    Write-Host "`n[2/3] Resetting the HeliosView submodule..." -ForegroundColor Cyan

    if (Get-Command git -ErrorAction SilentlyContinue) {
        Write-Host "  Deinitializing HeliosView..." -ForegroundColor DarkGray
        [void](Invoke-Native -FilePath 'git' -Arguments @('submodule', 'deinit', '-f', '--', 'HeliosView'))

        # Drop the submodule.HeliosView keys the deinit leaves behind.
        Write-Host "  Pruning submodule keys from .git/config..." -ForegroundColor DarkGray
        foreach ($line in (Get-NativeOutput -FilePath 'git' -Arguments @('config', '--get-regexp', '^submodule\.'))) {
            $key = ($line -split '\s+')[0]
            if ($key) { [void](Invoke-Native -FilePath 'git' -Arguments @('config', '--unset', $key)) }
        }

        if (-not $KeepGitCache) {
            $gitModulesDir = Join-Path $RepoRoot '.git\modules\HeliosView'
            if (Test-Path $gitModulesDir) {
                Write-Host "  Removing git module cache: $gitModulesDir..." -ForegroundColor DarkGray
                Remove-Item -Path $gitModulesDir -Recurse -Force -ErrorAction SilentlyContinue
            }
        } else {
            Write-Host "  -KeepGitCache specified: keeping .git/modules/HeliosView cache." -ForegroundColor Green
        }
    } else {
        Write-Warning "git command not found; removing the worktree directory only."
    }

    $heliosViewDir = Join-Path $RepoRoot 'HeliosView'
    if (Test-Path $heliosViewDir) {
        Write-Host "  Removing worktree: HeliosView..." -ForegroundColor DarkGray
        Remove-Item -Path $heliosViewDir -Recurse -Force -ErrorAction SilentlyContinue
    }
    Write-Host "  [DONE] HeliosView submodule has been deinitialized and removed." -ForegroundColor Green
} else {
    Write-Host "`n[2/3] Skipping the HeliosView submodule (-OnlyDownloads specified)." -ForegroundColor DarkGray
}

# ---------------------------------------------------------------------
# 3. Frontend dependencies
# ---------------------------------------------------------------------
$nodeModules = Join-Path $RepoRoot 'frontend/node_modules'

if ($OnlyDownloads -or $OnlySubmodules) {
    Write-Host "`n[3/3] Skipping frontend dependencies (-OnlyDownloads / -OnlySubmodules specified)." -ForegroundColor DarkGray
} elseif ($KeepFrontend) {
    Write-Host "`n[3/3] -KeepFrontend specified: keeping frontend/node_modules." -ForegroundColor Green
} elseif (Test-Path $nodeModules) {
    Write-Host "`n[3/3] Removing frontend/node_modules..." -ForegroundColor Cyan
    Remove-Item -Path $nodeModules -Recurse -Force -ErrorAction SilentlyContinue
    Write-Host "  [REMOVED] frontend/node_modules" -ForegroundColor Green
} else {
    Write-Host "`n[3/3] frontend/node_modules not present (already clean)." -ForegroundColor DarkGray
}

Write-Host "`n==========================================================" -ForegroundColor Yellow
Write-Host " Repository reset complete!" -ForegroundColor Green
Write-Host " Submodules are uninitialized and external resources removed." -ForegroundColor Green
Write-Host " Your development code and git branches are intact." -ForegroundColor Green
Write-Host " To re-initialize at any time, run:" -ForegroundColor Cyan
Write-Host "   scripts\setup-dependencies.cmd" -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Yellow
